version: '3.8'
services:
  express-gateway:
    build: ./express-gateway
      - context:
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ADMIN_GATEWAY_PASSWORD: ${ADMIN_GATEWAY_PASSWORD}
      REDIS_PROD_PASSWORD: ${REDIS_PROD_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    volumes:
      - .:/usr/src/api-gateway
      - /usr/src/api-gateway/node_modules
    networks:
      - express-gateway-network

networks:
  express-gateway-network:
    driver: bridge