http:
  port: ${PORT}

apiEndpoints:
  api:
    host: 'localhost'
    paths: '/api/*'

serviceEndpoints:
  userService:
    url: 'http://localhost:3001'

policies:
  - log
  - proxy
  - cors
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - log:
          - action:
              message: "Method: ${req.method}, URL: ${req.originalUrl}, IP: ${req.ip}, Body: ${JSON.stringify(req.body)}, Response Time: ${res.responseTime}ms"
      - cors:
          - action:
              origin: '*'
              methods: 'GET,POST,PUT,DELETE'
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
