version: '3.8'
services:
  app-booking-service:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db-booking-service
    env_file:
      - .env
    volumes:
      - .:/usr/src/booking-service
      - /usr/src/booking-service/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always
    command: ["./wait-for-it.sh", "db-booking-service:3306", "--", "npm", "start"]
    networks:
      - booking-service-network

  db-booking-service:
    image: mysql:5.7
    ports:
      - "3308:3308"
    expose:
        - "3308"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - booking-service-network

networks:
  booking-service-network:
    driver: bridge

volumes:
  db_data:
