version: '3.8'
services:
  app-booking-service:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db-booking-service
    env_file:
      - .env
    volumes:
      - .:/usr/src/booking-service
      - /usr/src/booking-service/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    command: npm start

  db-booking-service:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d/init_gymnest_booking_db.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
