version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
      - "REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}"
      - "REACT_APP_GOOGLE_CLIENT_SECRET=${REACT_APP_GOOGLE_CLIENT_SECRET}"
      - "REACT_APP_PAYPAL_CLIENT_ID=${REACT_APP_PAYPAL_CLIENT_ID}"
      - "REACT_APP_PAYPAL_CLIENT_SECRET=${REACT_APP_PAYPAL_CLIENT_SECRET}"
      - "GATEWAY_MAIN_URL=${GATEWAY_MAIN_URL}"