version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development