version: '3.8'
services:
  app-user-management-service:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db-user-management-service
    env_file:
      - .env
    volumes:
      - .:/usr/src/user-management-service
      - /usr/src/user-management-service/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: always
    command: ["./wait-for-it.sh", "db-user-management-service:3306", "--", "npm", "start"]
    networks:
      - user-service-network

  db-user-management-service:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./user-management-service/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge

volumes:
  db_data: