-- GymNestBookingDB

CREATE DATABASE IF NOT EXISTS GymNestBookingDB;
USE GymNestBookingDB;

CREATE TABLE IF NOT EXISTS Activities (
    ActivityID INT AUTO_INCREMENT PRIMARY KEY,
    ActivityName VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Schedules (
    ScheduleID INT AUTO_INCREMENT PRIMARY KEY,
    ActivityID INT,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    FOREIGN KEY (ActivityID) REFERENCES Activities(ActivityID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bookings (
    BookingID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ScheduleID INT,
    BookingDate DATETIME NOT NULL,
    FOREIGN KEY (ScheduleID) REFERENCES Schedules(ScheduleID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES GymNestUserDB.Users(UserID) ON DELETE CASCADE
);
