http:
  port: ${PORT_EXPRESS_GATEWAY}

admin:
  port: 9876
  host: localhost

db:
  redis:
    emulate: true
    namespace: EG

log:
  - name: default
    level: info
    streams:
      - stream: stdout
        level: debug

apiEndpoints:
  api:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']

serviceEndpoints:
  apiService:
    url: 'http://app-api-gateway:3004'

policies:
  cors:
    - action:
        origin: ['http://localhost:3000', 'http://localhost:3001', 'http://localhost:3002', 'http://localhost:3003', 'http://localhost:3004', 'http://localhost:3005']
  rateLimit:
    - action:
        max: 100
        windowMs: 60000 # 1 minute
