# system.config.yml
http:
  port: ${PORT_EXPRESS_GATEWAY}

admin:
  port: 9876
  host: localhost

db:
  redis:
    emulate: true
    namespace: EG

log:
  - name: default
    level: info
    streams:
      - stream: stdout
        level: debug

apiEndpoints:
  api:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api"
  auth:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/auth/*"
  users:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/users/*"
  roles:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/roles/*"
  memberships:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/memberships/*"
  payments:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/payments/*"
  bookings:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/bookings/*"
  activities:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/activities/*"
  schedules:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/schedules/*"
  notifications:
    host: "*"
    methods: [ "HEAD", "GET", "POST", "PUT", "DELETE" ]
    paths: "/api/notifications/*"

serviceEndpoints:
  apiService:
    url: "http://app-api-gateway:3004"# "http://express-gateway-service:3005" způsůbí log storm (problémy s přesměrováním)
  userService:
    url: "http://app-user-management-service:3001"
  membershipService:
    url: "http://app-membership-service:3002"#, "http://app-management-service:3002", "http://localhost:3002"]
  bookingService:
    url: "http://app-booking-service:3003"#, "http://localhost:3003"]
policies:
  - proxy
  - log
  - basic-auth
  - expression
  - cors
  - key-auth
  - oauth2
  - rate-limit
