http:
  port: ${PORT_EXPRESS_GATEWAY}

admin:
  port: 9876
  host: localhost

log:
  - name: default
    level: info
    streams:
      - stream: stdout
        level: debug

apiEndpoints:
  api:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
  auth:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: ['/auth', '/auth/*']
  authGoogle:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: ['/auth/google/','/auth/google/*']
  users:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: ['/users/', '/users/*']
  profiles:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: '/profiles/*'
  roles:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: '/roles/*'
  memberships:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'memberships/*'
  payments:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'api/payments/*'
  subscriptions:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'api/subscriptions/*'
  bookings:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'api/bookings/*'
  activities:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'api/activities/*'
  schedules:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: 'api/schedules/*'
  swagger:
    host: '*'
    methods: ['POST', 'GET', 'PUT', 'DELETE']
    paths: '/docs'

serviceEndpoints:
  apiService:
    url: 'http://app-api-gateway:3004'
  userService:
    url: 'http://app-user-management-service:3001/api'
  membershipService:
    url: 'http://app-management-service:3002/api'
  bookingService:
    url: 'http://app-booking-service:3003/api'
  swaggerService:
    url: 'http://frontend:3000/docs'

policies:
  - proxy
  - jwt
  - log
  - basic-auth
  - cors
  - expression
  - key-auth
  - oauth2
  - rate-limit

pipelines:
  apiPipeline:
    apiEndpoints:
      - api
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: apiService
  userPipeline:
    apiEndpoints:
      - auth
      - authGoogle
      - users
      - profiles
      - roles
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: userService
  membershipPipeline:
    apiEndpoints:
      - memberships
      - payments
      - subscriptions
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: membershipService
  bookingPipeline:
    apiEndpoints:
      - activity
      - bookings
      - activities
      - schedules
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: bookingService
  swaggerPipeline:
    apiEndpoints:
      - swagger
    policies:
      - proxy:
          - action:
              serviceEndpoint: swaggerService
