version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/usr/src/api-gateway
      - /usr/src/api-gateway/node_modules