http:
  port: 8080

apiEndpoints:
  auth:
    host: '*'
    paths: '/auth/*'
  users:
    host: '*'
    paths: '/users/*'
  profiles:
    host: '*'
    paths: '/profiles/*'
  roles:
    host: '*'
    paths: '/roles/*'
  memberships:
    host: '*'
    paths: '/memberships/*'
  payments:
    host: '*'
    paths: '/payments/*'
  subscriptions:
    host: '*'
    paths: '/subscriptions/*'
  bookings:
    host: '*'
    paths: '/bookings/*'
  activities:
    host: '*'
    paths: '/activities/*'
  schedules:
    host: '*'
    paths: '/schedules/*'
  swagger:
    host: '*'
    paths: '/docs'

serviceEndpoints:
  userService:
    url: 'http://user-management-service:3001'
  membershipService:
    url: 'http://membership-service:3002'
  bookingService:
    url: 'http://booking-service:3003'
  swaggerService:
    url: 'http://localhost:3000/docs'

policies:
  - proxy:
      - action:
          changeOrigin: true
  #- jwt:
  #    - action:
  #        secretOrPublicKeyFile: '.env/' // TODO - To je špatně, ale nevím, jak to správně nastavit
  #        checkCredentialExistence: false
  - log:
      - action:
          message: "{req.method} {req.originalUrl} ${JSON.stringify(req.headers)}"
  - proxy:
      - action:
          serviceEndpoint: swaggerService
          changeOrigin: true

pipelines:
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: userService
  userPipeline:
    apiEndpoints:
      - users
      - profiles
      - roles
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: userService
  membershipPipeline:
    apiEndpoints:
      - memberships
      - payments
      - subscriptions
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: membershipService
  bookingPipeline:
    apiEndpoints:
      - bookings
      - activities
      - schedules
    policies:
      - log:
          - action:
              message: "Request to ${req.method} ${req.originalUrl} with headers ${JSON.stringify(req.headers)}"
      - proxy:
          - action:
              serviceEndpoint: bookingService
  swaggerPipeline:
    apiEndpoints:
      - swagger
    policies:
      - proxy:
          - action:
              serviceEndpoint: swaggerService