version: '3.8'
services:
  app-management-service:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db-management-service
    env_file:
      - .env
    volumes:
      - .:/usr/src/member-service
      - /usr/src/member-service/node_modules
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    command: npm start
    networks:
      - membership-service-network

  db-management-service:
    image: mysql:5.7
    ports:
      - "3307:3307"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - membership-service-network

networks:
  membership-service-network:
    driver: bridge

volumes:
  db_data:
