version: '3.8'
services:
  app-management-service:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db-membership-service
    env_file:
      - .env
    volumes:
      - .:/usr/src/member-service
      - /usr/src/member-service/node_modules
    environment:
      DB_HOST: ${DB_HOST_MS}
      DB_USER: ${DB_USER_MS}
      DB_PASSWORD: ${DB_PASSWORD_MS}
      DB_NAME: ${DB_NAME_MS}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    restart: always
    command: ["./wait-for-it.sh", "db-user-membership-service:3307", "--", "npm", "start"]
    networks:
      - membership-service-network

  db-membership-service:
    image: mysql:8.3.0
    ports:
      - "3307:3307"
    expose:
      - "3307"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME_MS}
      MYSQL_USER: ${DB_USER_MS}
      MYSQL_PASSWORD: ${DB_PASSWORD_MS}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_MS}
    restart: always
    volumes:
      - db_data_membership:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - membership-service-network

networks:
  membership-service-network:
    driver: bridge

volumes:
  db_data_membership:
